var interaction1 = [
    {
        "int_id": 1,
        "grp_id": 1,
        "usr_id": 1,
        "grp_name": "CSC 492 : Senior Design",
        "usr_first_name": "Kevin",
        "usr_last_name": "Shah",
        "usr_email": "kshah7@ncsu.edu",
        "usr_unity_id": "kshah",
        "int_irl_id": 2,
        "irl_name": "Student",
        "not_title": "CSC 492 Note 1",
        "not_text": "Welcome to CSC 492 Kevin",
        "int_start_prd_id": 1,
        "start_period": "Spring",
        "start_year": 2021,
        "int_end_prd_id": 1,
        "end_period": "Spring",
        "end_year": 2021
    },
    {
        "int_id": 2,
        "grp_id": 1,
        "usr_id": 2,
        "grp_name": "CSC 492 : Senior Design",
        "usr_first_name": "Baris",
        "usr_last_name": "Akdogan",
        "usr_email": "bbakdoga@ncsu.edu",
        "usr_unity_id": "bbakdoga",
        "int_irl_id": 2,
        "irl_name": "Student",
        "not_title": "CSC 492 Note 1",
        "not_text": "Welcome to CSC 492 Baris",
        "int_start_prd_id": 1,
        "start_period": "Spring",
        "start_year": 2021,
        "int_end_prd_id": 1,
        "end_period": "Spring",
        "end_year": 2021
    },
    {
        "int_id": 3,
        "grp_id": 1,
        "usr_id": 3,
        "grp_name": "CSC 492 : Senior Design",
        "usr_first_name": "Abby",
        "usr_last_name": "Nuccio",
        "usr_email": "atnuccio@ncsu.edu",
        "usr_unity_id": "atnuccio",
        "int_irl_id": 2,
        "irl_name": "Student",
        "not_title": "CSC 492 Note 1",
        "not_text": "Welcome to CSC 492 Abby",
        "int_start_prd_id": 1,
        "start_period": "Spring",
        "start_year": 2021,
        "int_end_prd_id": 1,
        "end_period": "Spring",
        "end_year": 2021
    },
    {
        "int_id": 4,
        "grp_id": 1,
        "usr_id": 4,
        "grp_name": "CSC 492 : Senior Design",
        "usr_first_name": "Mustafa",
        "usr_last_name": "Sayeed",
        "usr_email": "mtsayeed@ncsu.edu",
        "usr_unity_id": "mtsayeed",
        "int_irl_id": 2,
        "irl_name": "Student",
        "not_title": "CSC 492 Note 1",
        "not_text": "Welcome to CSC 492 Mustafa",
        "int_start_prd_id": 1,
        "start_period": "Spring",
        "start_year": 2021,
        "int_end_prd_id": 1,
        "end_period": "Spring",
        "end_year": 2021
    },
    {
        "int_id": 5,
        "grp_id": 1,
        "usr_id": 5,
        "grp_name": "CSC 492 : Senior Design",
        "usr_first_name": "Judd",
        "usr_last_name": "Rollins",
        "usr_email": "hjrolli2@ncsu.edu",
        "usr_unity_id": "hjrolli2",
        "int_irl_id": 2,
        "irl_name": "Student",
        "not_title": "CSC 492 Note 1",
        "not_text": "Welcome to CSC 492 Judd",
        "int_start_prd_id": 1,
        "start_period": "Spring",
        "start_year": 2021,
        "int_end_prd_id": 1,
        "end_period": "Spring",
        "end_year": 2021
    },
    {
        "int_id": 6,
        "grp_id": 1,
        "usr_id": 6,
        "grp_name": "CSC 492 : Senior Design",
        "usr_first_name": "Ignacio",
        "usr_last_name": "Dominguez",
        "usr_email": "ixdoming@ncsu.edu",
        "usr_unity_id": "ixdoming",
        "int_irl_id": 1,
        "irl_name": "Professor",
        "not_title": null,
        "not_text": null,
        "int_start_prd_id": 1,
        "start_period": "Spring",
        "start_year": 2021,
        "int_end_prd_id": 1,
        "end_period": "Spring",
        "end_year": 2021
    },
    {
        "int_id": 7,
        "grp_id": 1,
        "usr_id": 7,
        "grp_name": "CSC 492 : Senior Design",
        "usr_first_name": "Colin",
        "usr_last_name": "Potts",
        "usr_email": "cmpotts@ncsu.edu",
        "usr_unity_id": "cmpotts",
        "int_irl_id": 3,
        "irl_name": "Assistant",
        "not_title": null,
        "not_text": null,
        "int_start_prd_id": 1,
        "start_period": "Spring",
        "start_year": 2021,
        "int_end_prd_id": 1,
        "end_period": "Spring",
        "end_year": 2021
    }
]

var interaction2 = [
    {
        "int_id": 8,
        "grp_id": 2,
        "usr_id": 1,
        "grp_name": "CSC 433 : Privacy",
        "usr_first_name": "Kevin",
        "usr_last_name": "Shah",
        "usr_email": "kshah7@ncsu.edu",
        "usr_unity_id": "kshah",
        "int_irl_id": 2,
        "irl_name": "Student",
        "not_title": "CSC 433 Note 1",
        "not_text": "Welcome to CSC 433 Kevin",
        "int_start_prd_id": 3,
        "start_period": "Fall",
        "start_year": 2020,
        "int_end_prd_id": 3,
        "end_period": "Fall",
        "end_year": 2020
    },
    {
        "int_id": 9,
        "grp_id": 2,
        "usr_id": 2,
        "grp_name": "CSC 433 : Privacy",
        "usr_first_name": "Baris",
        "usr_last_name": "Akdogan",
        "usr_email": "bbakdoga@ncsu.edu",
        "usr_unity_id": "bbakdoga",
        "int_irl_id": 2,
        "irl_name": "Student",
        "not_title": "CSC 433 Note 1",
        "not_text": "Welcome to CSC 433 Baris",
        "int_start_prd_id": 3,
        "start_period": "Fall",
        "start_year": 2020,
        "int_end_prd_id": 3,
        "end_period": "Fall",
        "end_year": 2020
    }
]

var interaction3 = [
    {
        "int_id": 10,
        "grp_id": 3,
        "usr_id": 4,
        "grp_name": "Robotics Club",
        "usr_first_name": "Mustafa",
        "usr_last_name": "Sayeed",
        "usr_email": "mtsayeed@ncsu.edu",
        "usr_unity_id": "mtsayeed",
        "int_irl_id": 2,
        "irl_name": "Student",
        "not_title": "CSC 411 Note 1",
        "not_text": "Welcome to Robotics Club Mustafa",
        "int_start_prd_id": 1,
        "start_period": "Spring",
        "start_year": 2017,
        "int_end_prd_id": 1,
        "end_period": "Spring",
        "end_year": 2018
    },
    {
        "int_id": 11,
        "grp_id": 3,
        "usr_id": 1,
        "grp_name": "Robotics Club",
        "usr_first_name": "Kevin",
        "usr_last_name": "Shah",
        "usr_email": "kshah7@ncsu.edu",
        "usr_unity_id": "kshah",
        "int_irl_id": 2,
        "irl_name": "Student",
        "not_title": "CSC 411 Note 1",
        "not_text": "Welcome to Robotics Club Kevin",
        "int_start_prd_id": 1,
        "start_period": "Spring",
        "start_year": 2018,
        "int_end_prd_id": 3,
        "end_period": "Fall",
        "end_year": 2019
    }
]

var interaction4 = [
    {
        "int_id": 12,
        "grp_id": 4,
        "usr_id": 4,
        "grp_name": "HackPack",
        "usr_first_name": "Mustafa",
        "usr_last_name": "Sayeed",
        "usr_email": "mtsayeed@ncsu.edu",
        "usr_unity_id": "mtsayeed",
        "int_irl_id": 2,
        "irl_name": "Student",
        "not_title": "CSC 422 Note 1",
        "not_text": "Welcome to Hackpack Mustafa",
        "int_start_prd_id": 3,
        "start_period": "Fall",
        "start_year": 2018,
        "int_end_prd_id": null,
        "end_period": null,
        "end_year": null
    }
]

module.exports = {
    interaction1,
    interaction2,
    interaction3,
    interaction4
}